user_name = "Mackenzie Leng"
resides_in = "Durango, CO"
spouse = "Zachary Brinkman"
my_age = 32
number_of_sibilings = 2
desired_salary = 130000.00
dog_age = 6.5
own_house = true
co_resident = true
co_native = false
user_name = "Emilie Young"
resides_in = "Chattanooga, TN"
spouse = "Ross Young"
